# Generated by Django 5.1.1 on 2024-12-27 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_dishes'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dishes',
            new_name='Dish',
        ),
    ]
