# Generated by Django 5.1.1 on 2024-12-28 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_rename_dishes_dish'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='menus.category'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='shops.shop'),
        ),
    ]
