# Generated by Django 5.1.1 on 2024-12-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0006_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='slug',
            field=models.SlugField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='', max_length=100),
        ),
    ]
