# Generated by Django 5.1.1 on 2024-12-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0007_dish_slug_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dish',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
    ]
